### ISSUE TITLE
Never gave definition of effect size

### ISSUE THREAD

**Issue by MNLKuzmin** [learn-co-curriculum/dsc-one-sample-t-tests-lab#3]
## Link to Canvas

https://flatiron.illumidesk.com/user/marianlkuzmin/notebooks/dsc-one-sample-t-tests-lab/index.ipynb
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X] Instructions unclear
- [ ] Other (explain below)

### Source

```
Bonus: What is the effect size of the first sample compared to the population? How can you interpret this effect size in relation to your significance test?
```

### Concern

We were never given a definition or explanation of effect size. I don't know if this was meant to be and we are supposed to study it elsewhere (like googling it) but it seemed strange that it's thrown there casually during an exercise when it was never mentioned before. Just wanted to point that out.

## (Optional) Proposed Solution

GIve in a previous lesson a definition or explanation of effect size, or explictly ask us to study it on our own so we can know it and use it. Thanks!

## What OS Are You Using?

- [X] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
We are revising this with an update to the curriculum.
